[project]
name = "event-driven-camera"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kaleido>=1.1.0",
    "lets-plot>=4.7.3",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "pydantic>=2.12.2",
    "pyyaml>=6.0.3",
    "scipy>=1.16.2",
]
